const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={view:location.hash.replace('#','')||'dashboard',items:[
{id:1,type:'prompt',title:'Prompt — Analista de mercado',content:'Pesquisa e síntese de concorrentes',tags:['ia','pesquisa'],favorite:true,updated:'Hoje, 18:22'},
{id:2,type:'password',title:'Conta principal',content:'login protegido',tags:['acesso'],favorite:false,updated:'Hoje, 16:05'},
{id:3,type:'note',title:'Ideias para projeto',content:'Rascunhos e decisões importantes',tags:['trabalho'],favorite:true,updated:'Ontem, 21:10'}]};
const labels={dashboard:'Visão geral',vault:'Cofre',prompts:'Prompts',passwords:'Senhas e logins',notes:'Notas',files:'Arquivos',favorites:'Favoritos',history:'Histórico',trash:'Lixeira',settings:'Configurações'};
function persist(){localStorage.setItem('ws_items',JSON.stringify(state.items))}try{const s=JSON.parse(localStorage.getItem('ws_items'));if(Array.isArray(s))state.items=s}catch{}
function metric(label,value){return `<div class="metric"><small>${label}</small><strong>${value}</strong></div>`}
function card(i){return `<div class="item-card"><div><h3>${escapeHtml(i.title)}</h3><p>${escapeHtml(i.content||'Sem descrição')} · ${escapeHtml(i.updated||'agora')}</p></div><span class="badge">${escapeHtml(i.type)}</span></div>`}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dashboard(){const p=state.items.filter(i=>i.type==='prompt').length, pw=state.items.filter(i=>i.type==='password').length, fav=state.items.filter(i=>i.favorite).length;return `<div class="hero"><div><span class="eyebrow">Seu espaço privado</span><h1>Work Storage</h1><p>Tudo o que você salva fica organizado para encontrar depois sem esforço.</p></div><button class="primary" onclick="openItem()">＋ Novo item</button></div><div class="metrics">${metric('Todos os itens',state.items.length)}${metric('Prompts',p)}${metric('Senhas e logins',pw)}${metric('Favoritos',fav)}</div><div class="grid-2"><div class="panel"><div class="panel-head"><h2>Recentes</h2><button class="ghost" onclick="go('vault')">Ver todos</button></div><div class="items">${state.items.slice(0,5).map(card).join('')||'<div class="empty">Seu cofre está vazio.</div>'}</div></div><div class="panel"><div class="panel-head"><h2>Acesso rápido</h2></div><div class="items"><button class="nav-item" onclick="go('prompts')">▤ Biblioteca de prompts</button><button class="nav-item" onclick="go('passwords')">⌕ Senhas e logins</button><button class="nav-item" onclick="go('notes')">▱ Notas rápidas</button></div></div></div>`}
function listView(view){let items=state.items;if(view==='prompts')items=items.filter(i=>i.type==='prompt');if(view==='passwords')items=items.filter(i=>i.type==='password');if(view==='notes')items=items.filter(i=>i.type==='note');if(view==='files')items=items.filter(i=>i.type==='file');if(view==='favorites')items=items.filter(i=>i.favorite);return `<div class="hero"><div><span class="eyebrow">Work Storage</span><h1>${labels[view]}</h1><p>${view==='vault'?'Todos os conteúdos guardados no seu cofre.':'Conteúdo organizado e pesquisável.'}</p></div><button class="primary" onclick="openItem()">＋ Novo item</button></div><div class="panel" style="margin-top:24px"><div class="items">${items.map(card).join('')||'<div class="empty">Nenhum item nesta seção.</div>'}</div></div>`}
function simple(view){const text={history:'Alterações recentes e versões aparecerão aqui.',trash:'Itens excluídos poderão ser restaurados antes da remoção definitiva.',settings:'Tema, segurança, bloqueio automático e conexão com Supabase serão configurados aqui.'}[view]||'';return `<div class="hero"><div><span class="eyebrow">Work Storage</span><h1>${labels[view]}</h1><p>${text}</p></div></div><div class="panel" style="margin-top:24px"><div class="empty">${text}</div></div>`}
function render(){state.view=location.hash.replace('#','')||'dashboard';$$('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#content').innerHTML=state.view==='dashboard'?dashboard():['vault','prompts','passwords','notes','files','favorites'].includes(state.view)?listView(state.view):simple(state.view)}
window.go=v=>{location.hash=v};window.addEventListener('hashchange',render);$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)go(b.dataset.view);$('.sidebar').classList.remove('open')});
window.openItem=()=>$('#itemDialog').showModal();$('#fab').onclick=openItem;$('#saveItem').onclick=e=>{e.preventDefault();const title=$('#itemTitle').value.trim();if(!title)return;state.items.unshift({id:Date.now(),type:$('#itemType').value,title,content:$('#itemContent').value.trim(),tags:$('#itemTags').value.split(',').map(x=>x.trim()).filter(Boolean),favorite:false,updated:'Agora'});persist();$('#itemForm').reset();$('#itemDialog').close();render()};
$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('ws_light',document.body.classList.contains('light')?'1':'0')};if(localStorage.getItem('ws_light')==='1')document.body.classList.add('light');$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();if(!q)return render();const matches=state.items.filter(i=>(i.title+' '+i.content+' '+(i.tags||[]).join(' ')).toLowerCase().includes(q));$('#content').innerHTML=`<div class="hero"><div><span class="eyebrow">Pesquisa</span><h1>Resultados</h1><p>${matches.length} item(ns) encontrado(s).</p></div></div><div class="panel" style="margin-top:24px"><div class="items">${matches.map(card).join('')||'<div class="empty">Nenhum resultado.</div>'}</div></div>`});
$('#lockBtn').onclick=()=>{$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')};$('#loginForm').addEventListener('submit',e=>{e.preventDefault();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden')});$('#togglePassword').onclick=()=>{$('#password').type=$('#password').type==='password'?'text':'password'};
render();